<?php

namespace Example;

/**
 * This class implements the unit tests for the Example application
 * It extends the Application class
 * 
 * It is used to test the Example application
 * It tests the framework utility libraries
 * 
 * @category   Example
 * @package    Example
 * @author     Nadir Latif <nadir@pakjiddat.com>
 * @license    https://www.gnu.org/licenses/gpl-2.0.html GNU General Public License, version 2
 * @version    1.0.0
 * @link       N.A
 */
class Example extends \Framework\Application\Application
{
    /** 
     * Handler function for index url option
	 *      		
     * @since 1.0.0		 		 
     * @param string $template_name the name of the template file to be rendered
     * @param array $template_parameters the template parameters generated by presentation function
     * 
     * @return array $template_parameters list of tag values for each tag in the template file defined in application configuration
     */
    public function HandleIndex($template_name, $template_parameters)
    {
         /** If the base_page.html template needs to be rendered, then its parameters are generated and returned */
        if ($template_name == "base_page.html") {
            /** The template parameters for base_page.html template are generated and returned. The returned templates will be used to generate the base_page.html template */
            $template_parameters = array(
                "title" => "Sample Application",
                "css_tags" => $template_parameters['css_tags'],
                "javascript_tags" => $template_parameters['javascript_tags']                
            );
        }
        /** If the list_page.html template needs to be rendered, then its parameters are generated and returned */
        else if ($template_name == "list_page.html") {
            /** The parameters for the list_page.html template are returned */
            $template_parameters = array(            	
                "list_page_title" => "Sample Application",               
                "framework_template_url" => $template_parameters['framework_template_url'],
                "table_data" => $template_parameters['table_html']                
            );
        }
        
        return $template_parameters;
    }

    /** 
     * Handler function for save url option
	 *      		
     * @since 1.0.0		 		 
     * 
     * @return array $data the data to be returned by the application
     */
    public function HandleSave()
    {
        $data = array("result"=>"success","message"=>"Controller function"); 
        
        return $data;
    } 
}